unit uTributosEAN;

interface

uses
   System.Generics.Collections, REST.Json.Types;

{$M+}

type
  TTributosDTO = class
  private
    FBase_Reduzida: string;
    FCest: string;
    FCesta_Basica: string;
    FCfop_Venda: string;
    FCod_Beneficio: string;
    FCodigo_Anp: string;
    FCodinterno_Cliente: string;
    FCofins: string;
    FDesc_Regra: string;
    FDescricao: string;
    FDescricao_Cliente: string;
    FDesoneracao_Descontar_Icms: Integer;
    FDesoneracao_Descontar_Piscofins: Integer;
    FDesoneracao_Motivo: string;
    FEan_Cliente: string;
    FIcms_Entrada: string;
    FIcms_Entrada_AC_Atacado: string;
    FIcms_Entrada_AC_Cd: string;
    FIcms_Entrada_AC_Industria: string;
    FIcms_Entrada_AL_Atacado: string;
    FIcms_Entrada_AL_Cd: string;
    FIcms_Entrada_AL_Industria: string;
    FIcms_Entrada_AM_Atacado: string;
    FIcms_Entrada_AM_Cd: string;
    FIcms_Entrada_AM_Industria: string;
    FIcms_Entrada_AP_Atacado: string;
    FIcms_Entrada_AP_Cd: string;
    FIcms_Entrada_AP_Industria: string;
    FIcms_Entrada_BA_Atacado: string;
    FIcms_Entrada_BA_Cd: string;
    FIcms_Entrada_BA_Industria: string;
    FIcms_Entrada_CE_Atacado: string;
    FIcms_Entrada_CE_Cd: string;
    FIcms_Entrada_CE_Industria: string;
    FIcms_Entrada_DF_Atacado: string;
    FIcms_Entrada_DF_Cd: string;
    FIcms_Entrada_DF_Industria: string;
    FIcms_Entrada_ES_Atacado: string;
    FIcms_Entrada_ES_Cd: string;
    FIcms_Entrada_ES_Industria: string;
    FIcms_Entrada_GO_Atacado: string;
    FIcms_Entrada_GO_Cd: string;
    FIcms_Entrada_GO_Industria: string;
    FIcms_Entrada_MA_Atacado: string;
    FIcms_Entrada_MA_Cd: string;
    FIcms_Entrada_MA_Industria: string;
    FIcms_Entrada_MG_Atacado: string;
    FIcms_Entrada_MG_Cd: string;
    FIcms_Entrada_MG_Industria: string;
    FIcms_Entrada_MS_Atacado: string;
    FIcms_Entrada_MS_Cd: string;
    FIcms_Entrada_MS_Industria: string;
    FIcms_Entrada_MT_Atacado: string;
    FIcms_Entrada_MT_Cd: string;
    FIcms_Entrada_MT_Industria: string;
    FIcms_Entrada_PA_Atacado: string;
    FIcms_Entrada_PA_Cd: string;
    FIcms_Entrada_PA_Industria: string;
    FIcms_Entrada_PB_Atacado: string;
    FIcms_Entrada_PB_Cd: string;
    FIcms_Entrada_PB_Industria: string;
    FIcms_Entrada_PE_Atacado: string;
    FIcms_Entrada_PE_Cd: string;
    FIcms_Entrada_PE_Industria: string;
    FIcms_Entrada_PI_Atacado: string;
    FIcms_Entrada_PI_Cd: string;
    FIcms_Entrada_PI_Industria: string;
    FIcms_Entrada_PR_Atacado: string;
    FIcms_Entrada_PR_Cd: string;
    FIcms_Entrada_PR_Industria: string;
    FIcms_Entrada_RJ_Atacado: string;
    FIcms_Entrada_RJ_Cd: string;
    FIcms_Entrada_RJ_Industria: string;
    FIcms_Entrada_RN_Atacado: string;
    FIcms_Entrada_RN_Cd: string;
    FIcms_Entrada_RN_Industria: string;
    FIcms_Entrada_RO_Atacado: string;
    FIcms_Entrada_RO_Cd: string;
    FIcms_Entrada_RO_Industria: string;
    FIcms_Entrada_RR_Atacado: string;
    FIcms_Entrada_RR_Cd: string;
    FIcms_Entrada_RR_Industria: string;
    FIcms_Entrada_RS_Atacado: string;
    FIcms_Entrada_RS_Cd: string;
    FIcms_Entrada_RS_Industria: string;
    FIcms_Entrada_SC_Atacado: string;
    FIcms_Entrada_SC_Cd: string;
    FIcms_Entrada_SC_Industria: string;
    FIcms_Entrada_SE_Atacado: string;
    FIcms_Entrada_SE_Cd: string;
    FIcms_Entrada_SE_Industria: string;
    FIcms_Entrada_SP_Atacado: string;
    FIcms_Entrada_SP_Cd: string;
    FIcms_Entrada_SP_Industria: string;
    FIcms_Entrada_TO_Atacado: string;
    FIcms_Entrada_TO_Cd: string;
    FIcms_Entrada_TO_Industria: string;
    FIcms_Fcp: string;
    FIcms_Saida: string;
    FIcms_Saida_Aliquota_Cheia: string;
    FIcms_Saida_Csosn: string;
    FIcms_Saida_Cst: string;
    FIcms_Saida_Percentual_Reducao: string;
    FIdlista: string;
    FIdproduto: string;
    FIdregra: string;
    FIdsegmento: string;
    FImportado: string;
    FIpi: string;
    FLista: string;
    FMercantil: string;
    FModalidade_Bc: Integer;
    FMva: string;
    FMva_Ajustado_AC_Atacado: string;
    FMva_Ajustado_AC_Cd: string;
    FMva_Ajustado_AC_Industria: string;
    FMva_Ajustado_AL_Atacado: string;
    FMva_Ajustado_AL_Cd: string;
    FMva_Ajustado_AL_Industria: string;
    FMva_Ajustado_AM_Atacado: string;
    FMva_Ajustado_AM_Cd: string;
    FMva_Ajustado_AM_Industria: string;
    FMva_Ajustado_AP_Atacado: string;
    FMva_Ajustado_AP_Cd: string;
    FMva_Ajustado_AP_Industria: string;
    FMva_Ajustado_BA_Atacado: string;
    FMva_Ajustado_BA_Cd: string;
    FMva_Ajustado_BA_Industria: string;
    FMva_Ajustado_CE_Atacado: string;
    FMva_Ajustado_CE_Cd: string;
    FMva_Ajustado_CE_Industria: string;
    FMva_Ajustado_DF_Atacado: string;
    FMva_Ajustado_DF_Cd: string;
    FMva_Ajustado_DF_Industria: string;
    FMva_Ajustado_ES_Atacado: string;
    FMva_Ajustado_ES_Cd: string;
    FMva_Ajustado_ES_Industria: string;
    FMva_Ajustado_GO_Atacado: string;
    FMva_Ajustado_GO_Cd: string;
    FMva_Ajustado_GO_Industria: string;
    FMva_Ajustado_MA_Atacado: string;
    FMva_Ajustado_MA_Cd: string;
    FMva_Ajustado_MA_Industria: string;
    FMva_Ajustado_MG_Atacado: string;
    FMva_Ajustado_MG_Cd: string;
    FMva_Ajustado_MG_Industria: string;
    FMva_Ajustado_MS_Atacado: string;
    FMva_Ajustado_MS_Cd: string;
    FMva_Ajustado_MS_Industria: string;
    FMva_Ajustado_MT_Atacado: string;
    FMva_Ajustado_MT_Cd: string;
    FMva_Ajustado_MT_Industria: string;
    FMva_Ajustado_PA_Atacado: string;
    FMva_Ajustado_PA_Cd: string;
    FMva_Ajustado_PA_Industria: string;
    FMva_Ajustado_PB_Atacado: string;
    FMva_Ajustado_PB_Cd: string;
    FMva_Ajustado_PB_Industria: string;
    FMva_Ajustado_PE_Atacado: string;
    FMva_Ajustado_PE_Cd: string;
    FMva_Ajustado_PE_Industria: string;
    FMva_Ajustado_PI_Atacado: string;
    FMva_Ajustado_PI_Cd: string;
    FMva_Ajustado_PI_Industria: string;
    FMva_Ajustado_PR_Atacado: string;
    FMva_Ajustado_PR_Cd: string;
    FMva_Ajustado_PR_Industria: string;
    FMva_Ajustado_RJ_Atacado: string;
    FMva_Ajustado_RJ_Cd: string;
    FMva_Ajustado_RJ_Industria: string;
    FMva_Ajustado_RN_Atacado: string;
    FMva_Ajustado_RN_Cd: string;
    FMva_Ajustado_RN_Industria: string;
    FMva_Ajustado_RO_Atacado: string;
    FMva_Ajustado_RO_Cd: string;
    FMva_Ajustado_RO_Industria: string;
    FMva_Ajustado_RR_Atacado: string;
    FMva_Ajustado_RR_Cd: string;
    FMva_Ajustado_RR_Industria: string;
    FMva_Ajustado_RS_Atacado: string;
    FMva_Ajustado_RS_Cd: string;
    FMva_Ajustado_RS_Industria: string;
    FMva_Ajustado_SC_Atacado: string;
    FMva_Ajustado_SC_Cd: string;
    FMva_Ajustado_SC_Industria: string;
    FMva_Ajustado_SE_Atacado: string;
    FMva_Ajustado_SE_Cd: string;
    FMva_Ajustado_SE_Industria: string;
    FMva_Ajustado_SP_Atacado: string;
    FMva_Ajustado_SP_Cd: string;
    FMva_Ajustado_SP_Industria: string;
    FMva_Ajustado_TO_Atacado: string;
    FMva_Ajustado_TO_Cd: string;
    FMva_Ajustado_TO_Industria: string;
    FMva_Importado: string;
    FNcm: string;
    FNcmex: string;
    FPauta: Integer;
    FPauta_Valor: string;
    FPis: string;
    FPiscofins_Cst_Entrada: string;
    FPiscofins_Cst_Saida: string;
    FPiscofins_Naturezarec: string;
    FPiscofins_Situacao: string;
    FSegmento: string;
    FSubitem: string;
    FSubstituicao_Tributaria: string;
    FMensagem   : String;
  published
    property Base_Reduzida: string read FBase_Reduzida write FBase_Reduzida;
    property Cest: string read FCest write FCest;
    property Cesta_Basica: string read FCesta_Basica write FCesta_Basica;
    property Cfop_Venda: string read FCfop_Venda write FCfop_Venda;
    property Cod_Beneficio: string read FCod_Beneficio write FCod_Beneficio;
    property Codigo_Anp: string read FCodigo_Anp write FCodigo_Anp;
    property Codinterno_Cliente: string read FCodinterno_Cliente write FCodinterno_Cliente;
    property Cofins: string read FCofins write FCofins;
    property Desc_Regra: string read FDesc_Regra write FDesc_Regra;
    property Descricao: string read FDescricao write FDescricao;
    property Descricao_Cliente: string read FDescricao_Cliente write FDescricao_Cliente;
    property Desoneracao_Descontar_Icms: Integer read FDesoneracao_Descontar_Icms write FDesoneracao_Descontar_Icms;
    property Desoneracao_Descontar_Piscofins: Integer read FDesoneracao_Descontar_Piscofins write FDesoneracao_Descontar_Piscofins;
    property Desoneracao_Motivo: string read FDesoneracao_Motivo write FDesoneracao_Motivo;
    property Ean_Cliente: string read FEan_Cliente write FEan_Cliente;
    property Icms_Entrada: string read FIcms_Entrada write FIcms_Entrada;
    property Icms_Entrada_AC_Atacado: string read FIcms_Entrada_AC_Atacado write FIcms_Entrada_AC_Atacado;
    property Icms_Entrada_AC_Cd: string read FIcms_Entrada_AC_Cd write FIcms_Entrada_AC_Cd;
    property Icms_Entrada_AC_Industria: string read FIcms_Entrada_AC_Industria write FIcms_Entrada_AC_Industria;
    property Icms_Entrada_AL_Atacado: string read FIcms_Entrada_AL_Atacado write FIcms_Entrada_AL_Atacado;
    property Icms_Entrada_AL_Cd: string read FIcms_Entrada_AL_Cd write FIcms_Entrada_AL_Cd;
    property Icms_Entrada_AL_Industria: string read FIcms_Entrada_AL_Industria write FIcms_Entrada_AL_Industria;
    property Icms_Entrada_AM_Atacado: string read FIcms_Entrada_AM_Atacado write FIcms_Entrada_AM_Atacado;
    property Icms_Entrada_AM_Cd: string read FIcms_Entrada_AM_Cd write FIcms_Entrada_AM_Cd;
    property Icms_Entrada_AM_Industria: string read FIcms_Entrada_AM_Industria write FIcms_Entrada_AM_Industria;
    property Icms_Entrada_AP_Atacado: string read FIcms_Entrada_AP_Atacado write FIcms_Entrada_AP_Atacado;
    property Icms_Entrada_AP_Cd: string read FIcms_Entrada_AP_Cd write FIcms_Entrada_AP_Cd;
    property Icms_Entrada_AP_Industria: string read FIcms_Entrada_AP_Industria write FIcms_Entrada_AP_Industria;
    property Icms_Entrada_BA_Atacado: string read FIcms_Entrada_BA_Atacado write FIcms_Entrada_BA_Atacado;
    property Icms_Entrada_BA_Cd: string read FIcms_Entrada_BA_Cd write FIcms_Entrada_BA_Cd;
    property Icms_Entrada_BA_Industria: string read FIcms_Entrada_BA_Industria write FIcms_Entrada_BA_Industria;
    property Icms_Entrada_CE_Atacado: string read FIcms_Entrada_CE_Atacado write FIcms_Entrada_CE_Atacado;
    property Icms_Entrada_CE_Cd: string read FIcms_Entrada_CE_Cd write FIcms_Entrada_CE_Cd;
    property Icms_Entrada_CE_Industria: string read FIcms_Entrada_CE_Industria write FIcms_Entrada_CE_Industria;
    property Icms_Entrada_DF_Atacado: string read FIcms_Entrada_DF_Atacado write FIcms_Entrada_DF_Atacado;
    property Icms_Entrada_DF_Cd: string read FIcms_Entrada_DF_Cd write FIcms_Entrada_DF_Cd;
    property Icms_Entrada_DF_Industria: string read FIcms_Entrada_DF_Industria write FIcms_Entrada_DF_Industria;
    property Icms_Entrada_ES_Atacado: string read FIcms_Entrada_ES_Atacado write FIcms_Entrada_ES_Atacado;
    property Icms_Entrada_ES_Cd: string read FIcms_Entrada_ES_Cd write FIcms_Entrada_ES_Cd;
    property Icms_Entrada_ES_Industria: string read FIcms_Entrada_ES_Industria write FIcms_Entrada_ES_Industria;
    property Icms_Entrada_GO_Atacado: string read FIcms_Entrada_GO_Atacado write FIcms_Entrada_GO_Atacado;
    property Icms_Entrada_GO_Cd: string read FIcms_Entrada_GO_Cd write FIcms_Entrada_GO_Cd;
    property Icms_Entrada_GO_Industria: string read FIcms_Entrada_GO_Industria write FIcms_Entrada_GO_Industria;
    property Icms_Entrada_MA_Atacado: string read FIcms_Entrada_MA_Atacado write FIcms_Entrada_MA_Atacado;
    property Icms_Entrada_MA_Cd: string read FIcms_Entrada_MA_Cd write FIcms_Entrada_MA_Cd;
    property Icms_Entrada_MA_Industria: string read FIcms_Entrada_MA_Industria write FIcms_Entrada_MA_Industria;
    property Icms_Entrada_MG_Atacado: string read FIcms_Entrada_MG_Atacado write FIcms_Entrada_MG_Atacado;
    property Icms_Entrada_MG_Cd: string read FIcms_Entrada_MG_Cd write FIcms_Entrada_MG_Cd;
    property Icms_Entrada_MG_Industria: string read FIcms_Entrada_MG_Industria write FIcms_Entrada_MG_Industria;
    property Icms_Entrada_MS_Atacado: string read FIcms_Entrada_MS_Atacado write FIcms_Entrada_MS_Atacado;
    property Icms_Entrada_MS_Cd: string read FIcms_Entrada_MS_Cd write FIcms_Entrada_MS_Cd;
    property Icms_Entrada_MS_Industria: string read FIcms_Entrada_MS_Industria write FIcms_Entrada_MS_Industria;
    property Icms_Entrada_MT_Atacado: string read FIcms_Entrada_MT_Atacado write FIcms_Entrada_MT_Atacado;
    property Icms_Entrada_MT_Cd: string read FIcms_Entrada_MT_Cd write FIcms_Entrada_MT_Cd;
    property Icms_Entrada_MT_Industria: string read FIcms_Entrada_MT_Industria write FIcms_Entrada_MT_Industria;
    property Icms_Entrada_PA_Atacado: string read FIcms_Entrada_PA_Atacado write FIcms_Entrada_PA_Atacado;
    property Icms_Entrada_PA_Cd: string read FIcms_Entrada_PA_Cd write FIcms_Entrada_PA_Cd;
    property Icms_Entrada_PA_Industria: string read FIcms_Entrada_PA_Industria write FIcms_Entrada_PA_Industria;
    property Icms_Entrada_PB_Atacado: string read FIcms_Entrada_PB_Atacado write FIcms_Entrada_PB_Atacado;
    property Icms_Entrada_PB_Cd: string read FIcms_Entrada_PB_Cd write FIcms_Entrada_PB_Cd;
    property Icms_Entrada_PB_Industria: string read FIcms_Entrada_PB_Industria write FIcms_Entrada_PB_Industria;
    property Icms_Entrada_PE_Atacado: string read FIcms_Entrada_PE_Atacado write FIcms_Entrada_PE_Atacado;
    property Icms_Entrada_PE_Cd: string read FIcms_Entrada_PE_Cd write FIcms_Entrada_PE_Cd;
    property Icms_Entrada_PE_Industria: string read FIcms_Entrada_PE_Industria write FIcms_Entrada_PE_Industria;
    property Icms_Entrada_PI_Atacado: string read FIcms_Entrada_PI_Atacado write FIcms_Entrada_PI_Atacado;
    property Icms_Entrada_PI_Cd: string read FIcms_Entrada_PI_Cd write FIcms_Entrada_PI_Cd;
    property Icms_Entrada_PI_Industria: string read FIcms_Entrada_PI_Industria write FIcms_Entrada_PI_Industria;
    property Icms_Entrada_PR_Atacado: string read FIcms_Entrada_PR_Atacado write FIcms_Entrada_PR_Atacado;
    property Icms_Entrada_PR_Cd: string read FIcms_Entrada_PR_Cd write FIcms_Entrada_PR_Cd;
    property Icms_Entrada_PR_Industria: string read FIcms_Entrada_PR_Industria write FIcms_Entrada_PR_Industria;
    property Icms_Entrada_RJ_Atacado: string read FIcms_Entrada_RJ_Atacado write FIcms_Entrada_RJ_Atacado;
    property Icms_Entrada_RJ_Cd: string read FIcms_Entrada_RJ_Cd write FIcms_Entrada_RJ_Cd;
    property Icms_Entrada_RJ_Industria: string read FIcms_Entrada_RJ_Industria write FIcms_Entrada_RJ_Industria;
    property Icms_Entrada_RN_Atacado: string read FIcms_Entrada_RN_Atacado write FIcms_Entrada_RN_Atacado;
    property Icms_Entrada_RN_Cd: string read FIcms_Entrada_RN_Cd write FIcms_Entrada_RN_Cd;
    property Icms_Entrada_RN_Industria: string read FIcms_Entrada_RN_Industria write FIcms_Entrada_RN_Industria;
    property Icms_Entrada_RO_Atacado: string read FIcms_Entrada_RO_Atacado write FIcms_Entrada_RO_Atacado;
    property Icms_Entrada_RO_Cd: string read FIcms_Entrada_RO_Cd write FIcms_Entrada_RO_Cd;
    property Icms_Entrada_RO_Industria: string read FIcms_Entrada_RO_Industria write FIcms_Entrada_RO_Industria;
    property Icms_Entrada_RR_Atacado: string read FIcms_Entrada_RR_Atacado write FIcms_Entrada_RR_Atacado;
    property Icms_Entrada_RR_Cd: string read FIcms_Entrada_RR_Cd write FIcms_Entrada_RR_Cd;
    property Icms_Entrada_RR_Industria: string read FIcms_Entrada_RR_Industria write FIcms_Entrada_RR_Industria;
    property Icms_Entrada_RS_Atacado: string read FIcms_Entrada_RS_Atacado write FIcms_Entrada_RS_Atacado;
    property Icms_Entrada_RS_Cd: string read FIcms_Entrada_RS_Cd write FIcms_Entrada_RS_Cd;
    property Icms_Entrada_RS_Industria: string read FIcms_Entrada_RS_Industria write FIcms_Entrada_RS_Industria;
    property Icms_Entrada_SC_Atacado: string read FIcms_Entrada_SC_Atacado write FIcms_Entrada_SC_Atacado;
    property Icms_Entrada_SC_Cd: string read FIcms_Entrada_SC_Cd write FIcms_Entrada_SC_Cd;
    property Icms_Entrada_SC_Industria: string read FIcms_Entrada_SC_Industria write FIcms_Entrada_SC_Industria;
    property Icms_Entrada_SE_Atacado: string read FIcms_Entrada_SE_Atacado write FIcms_Entrada_SE_Atacado;
    property Icms_Entrada_SE_Cd: string read FIcms_Entrada_SE_Cd write FIcms_Entrada_SE_Cd;
    property Icms_Entrada_SE_Industria: string read FIcms_Entrada_SE_Industria write FIcms_Entrada_SE_Industria;
    property Icms_Entrada_SP_Atacado: string read FIcms_Entrada_SP_Atacado write FIcms_Entrada_SP_Atacado;
    property Icms_Entrada_SP_Cd: string read FIcms_Entrada_SP_Cd write FIcms_Entrada_SP_Cd;
    property Icms_Entrada_SP_Industria: string read FIcms_Entrada_SP_Industria write FIcms_Entrada_SP_Industria;
    property Icms_Entrada_TO_Atacado: string read FIcms_Entrada_TO_Atacado write FIcms_Entrada_TO_Atacado;
    property Icms_Entrada_TO_Cd: string read FIcms_Entrada_TO_Cd write FIcms_Entrada_TO_Cd;
    property Icms_Entrada_TO_Industria: string read FIcms_Entrada_TO_Industria write FIcms_Entrada_TO_Industria;
    property Icms_Fcp: string read FIcms_Fcp write FIcms_Fcp;
    property Icms_Saida: string read FIcms_Saida write FIcms_Saida;
    property Icms_Saida_Aliquota_Cheia: string read FIcms_Saida_Aliquota_Cheia write FIcms_Saida_Aliquota_Cheia;
    property Icms_Saida_Csosn: string read FIcms_Saida_Csosn write FIcms_Saida_Csosn;
    property Icms_Saida_Cst: string read FIcms_Saida_Cst write FIcms_Saida_Cst;
    property Icms_Saida_Percentual_Reducao: string read FIcms_Saida_Percentual_Reducao write FIcms_Saida_Percentual_Reducao;
    property Idlista: string read FIdlista write FIdlista;
    property Idproduto: string read FIdproduto write FIdproduto;
    property Idregra: string read FIdregra write FIdregra;
    property Idsegmento: string read FIdsegmento write FIdsegmento;
    property Importado: string read FImportado write FImportado;
    property Ipi: string read FIpi write FIpi;
    property Lista: string read FLista write FLista;
    property Mercantil: string read FMercantil write FMercantil;
    property Modalidade_Bc: Integer read FModalidade_Bc write FModalidade_Bc;
    property Mva: string read FMva write FMva;
    property Mva_Ajustado_AC_Atacado: string read FMva_Ajustado_AC_Atacado write FMva_Ajustado_AC_Atacado;
    property Mva_Ajustado_AC_Cd: string read FMva_Ajustado_AC_Cd write FMva_Ajustado_AC_Cd;
    property Mva_Ajustado_AC_Industria: string read FMva_Ajustado_AC_Industria write FMva_Ajustado_AC_Industria;
    property Mva_Ajustado_AL_Atacado: string read FMva_Ajustado_AL_Atacado write FMva_Ajustado_AL_Atacado;
    property Mva_Ajustado_AL_Cd: string read FMva_Ajustado_AL_Cd write FMva_Ajustado_AL_Cd;
    property Mva_Ajustado_AL_Industria: string read FMva_Ajustado_AL_Industria write FMva_Ajustado_AL_Industria;
    property Mva_Ajustado_AM_Atacado: string read FMva_Ajustado_AM_Atacado write FMva_Ajustado_AM_Atacado;
    property Mva_Ajustado_AM_Cd: string read FMva_Ajustado_AM_Cd write FMva_Ajustado_AM_Cd;
    property Mva_Ajustado_AM_Industria: string read FMva_Ajustado_AM_Industria write FMva_Ajustado_AM_Industria;
    property Mva_Ajustado_AP_Atacado: string read FMva_Ajustado_AP_Atacado write FMva_Ajustado_AP_Atacado;
    property Mva_Ajustado_AP_Cd: string read FMva_Ajustado_AP_Cd write FMva_Ajustado_AP_Cd;
    property Mva_Ajustado_AP_Industria: string read FMva_Ajustado_AP_Industria write FMva_Ajustado_AP_Industria;
    property Mva_Ajustado_BA_Atacado: string read FMva_Ajustado_BA_Atacado write FMva_Ajustado_BA_Atacado;
    property Mva_Ajustado_BA_Cd: string read FMva_Ajustado_BA_Cd write FMva_Ajustado_BA_Cd;
    property Mva_Ajustado_BA_Industria: string read FMva_Ajustado_BA_Industria write FMva_Ajustado_BA_Industria;
    property Mva_Ajustado_CE_Atacado: string read FMva_Ajustado_CE_Atacado write FMva_Ajustado_CE_Atacado;
    property Mva_Ajustado_CE_Cd: string read FMva_Ajustado_CE_Cd write FMva_Ajustado_CE_Cd;
    property Mva_Ajustado_CE_Industria: string read FMva_Ajustado_CE_Industria write FMva_Ajustado_CE_Industria;
    property Mva_Ajustado_DF_Atacado: string read FMva_Ajustado_DF_Atacado write FMva_Ajustado_DF_Atacado;
    property Mva_Ajustado_DF_Cd: string read FMva_Ajustado_DF_Cd write FMva_Ajustado_DF_Cd;
    property Mva_Ajustado_DF_Industria: string read FMva_Ajustado_DF_Industria write FMva_Ajustado_DF_Industria;
    property Mva_Ajustado_ES_Atacado: string read FMva_Ajustado_ES_Atacado write FMva_Ajustado_ES_Atacado;
    property Mva_Ajustado_ES_Cd: string read FMva_Ajustado_ES_Cd write FMva_Ajustado_ES_Cd;
    property Mva_Ajustado_ES_Industria: string read FMva_Ajustado_ES_Industria write FMva_Ajustado_ES_Industria;
    property Mva_Ajustado_GO_Atacado: string read FMva_Ajustado_GO_Atacado write FMva_Ajustado_GO_Atacado;
    property Mva_Ajustado_GO_Cd: string read FMva_Ajustado_GO_Cd write FMva_Ajustado_GO_Cd;
    property Mva_Ajustado_GO_Industria: string read FMva_Ajustado_GO_Industria write FMva_Ajustado_GO_Industria;
    property Mva_Ajustado_MA_Atacado: string read FMva_Ajustado_MA_Atacado write FMva_Ajustado_MA_Atacado;
    property Mva_Ajustado_MA_Cd: string read FMva_Ajustado_MA_Cd write FMva_Ajustado_MA_Cd;
    property Mva_Ajustado_MA_Industria: string read FMva_Ajustado_MA_Industria write FMva_Ajustado_MA_Industria;
    property Mva_Ajustado_MG_Atacado: string read FMva_Ajustado_MG_Atacado write FMva_Ajustado_MG_Atacado;
    property Mva_Ajustado_MG_Cd: string read FMva_Ajustado_MG_Cd write FMva_Ajustado_MG_Cd;
    property Mva_Ajustado_MG_Industria: string read FMva_Ajustado_MG_Industria write FMva_Ajustado_MG_Industria;
    property Mva_Ajustado_MS_Atacado: string read FMva_Ajustado_MS_Atacado write FMva_Ajustado_MS_Atacado;
    property Mva_Ajustado_MS_Cd: string read FMva_Ajustado_MS_Cd write FMva_Ajustado_MS_Cd;
    property Mva_Ajustado_MS_Industria: string read FMva_Ajustado_MS_Industria write FMva_Ajustado_MS_Industria;
    property Mva_Ajustado_MT_Atacado: string read FMva_Ajustado_MT_Atacado write FMva_Ajustado_MT_Atacado;
    property Mva_Ajustado_MT_Cd: string read FMva_Ajustado_MT_Cd write FMva_Ajustado_MT_Cd;
    property Mva_Ajustado_MT_Industria: string read FMva_Ajustado_MT_Industria write FMva_Ajustado_MT_Industria;
    property Mva_Ajustado_PA_Atacado: string read FMva_Ajustado_PA_Atacado write FMva_Ajustado_PA_Atacado;
    property Mva_Ajustado_PA_Cd: string read FMva_Ajustado_PA_Cd write FMva_Ajustado_PA_Cd;
    property Mva_Ajustado_PA_Industria: string read FMva_Ajustado_PA_Industria write FMva_Ajustado_PA_Industria;
    property Mva_Ajustado_PB_Atacado: string read FMva_Ajustado_PB_Atacado write FMva_Ajustado_PB_Atacado;
    property Mva_Ajustado_PB_Cd: string read FMva_Ajustado_PB_Cd write FMva_Ajustado_PB_Cd;
    property Mva_Ajustado_PB_Industria: string read FMva_Ajustado_PB_Industria write FMva_Ajustado_PB_Industria;
    property Mva_Ajustado_PE_Atacado: string read FMva_Ajustado_PE_Atacado write FMva_Ajustado_PE_Atacado;
    property Mva_Ajustado_PE_Cd: string read FMva_Ajustado_PE_Cd write FMva_Ajustado_PE_Cd;
    property Mva_Ajustado_PE_Industria: string read FMva_Ajustado_PE_Industria write FMva_Ajustado_PE_Industria;
    property Mva_Ajustado_PI_Atacado: string read FMva_Ajustado_PI_Atacado write FMva_Ajustado_PI_Atacado;
    property Mva_Ajustado_PI_Cd: string read FMva_Ajustado_PI_Cd write FMva_Ajustado_PI_Cd;
    property Mva_Ajustado_PI_Industria: string read FMva_Ajustado_PI_Industria write FMva_Ajustado_PI_Industria;
    property Mva_Ajustado_PR_Atacado: string read FMva_Ajustado_PR_Atacado write FMva_Ajustado_PR_Atacado;
    property Mva_Ajustado_PR_Cd: string read FMva_Ajustado_PR_Cd write FMva_Ajustado_PR_Cd;
    property Mva_Ajustado_PR_Industria: string read FMva_Ajustado_PR_Industria write FMva_Ajustado_PR_Industria;
    property Mva_Ajustado_RJ_Atacado: string read FMva_Ajustado_RJ_Atacado write FMva_Ajustado_RJ_Atacado;
    property Mva_Ajustado_RJ_Cd: string read FMva_Ajustado_RJ_Cd write FMva_Ajustado_RJ_Cd;
    property Mva_Ajustado_RJ_Industria: string read FMva_Ajustado_RJ_Industria write FMva_Ajustado_RJ_Industria;
    property Mva_Ajustado_RN_Atacado: string read FMva_Ajustado_RN_Atacado write FMva_Ajustado_RN_Atacado;
    property Mva_Ajustado_RN_Cd: string read FMva_Ajustado_RN_Cd write FMva_Ajustado_RN_Cd;
    property Mva_Ajustado_RN_Industria: string read FMva_Ajustado_RN_Industria write FMva_Ajustado_RN_Industria;
    property Mva_Ajustado_RO_Atacado: string read FMva_Ajustado_RO_Atacado write FMva_Ajustado_RO_Atacado;
    property Mva_Ajustado_RO_Cd: string read FMva_Ajustado_RO_Cd write FMva_Ajustado_RO_Cd;
    property Mva_Ajustado_RO_Industria: string read FMva_Ajustado_RO_Industria write FMva_Ajustado_RO_Industria;
    property Mva_Ajustado_RR_Atacado: string read FMva_Ajustado_RR_Atacado write FMva_Ajustado_RR_Atacado;
    property Mva_Ajustado_RR_Cd: string read FMva_Ajustado_RR_Cd write FMva_Ajustado_RR_Cd;
    property Mva_Ajustado_RR_Industria: string read FMva_Ajustado_RR_Industria write FMva_Ajustado_RR_Industria;
    property Mva_Ajustado_RS_Atacado: string read FMva_Ajustado_RS_Atacado write FMva_Ajustado_RS_Atacado;
    property Mva_Ajustado_RS_Cd: string read FMva_Ajustado_RS_Cd write FMva_Ajustado_RS_Cd;
    property Mva_Ajustado_RS_Industria: string read FMva_Ajustado_RS_Industria write FMva_Ajustado_RS_Industria;
    property Mva_Ajustado_SC_Atacado: string read FMva_Ajustado_SC_Atacado write FMva_Ajustado_SC_Atacado;
    property Mva_Ajustado_SC_Cd: string read FMva_Ajustado_SC_Cd write FMva_Ajustado_SC_Cd;
    property Mva_Ajustado_SC_Industria: string read FMva_Ajustado_SC_Industria write FMva_Ajustado_SC_Industria;
    property Mva_Ajustado_SE_Atacado: string read FMva_Ajustado_SE_Atacado write FMva_Ajustado_SE_Atacado;
    property Mva_Ajustado_SE_Cd: string read FMva_Ajustado_SE_Cd write FMva_Ajustado_SE_Cd;
    property Mva_Ajustado_SE_Industria: string read FMva_Ajustado_SE_Industria write FMva_Ajustado_SE_Industria;
    property Mva_Ajustado_SP_Atacado: string read FMva_Ajustado_SP_Atacado write FMva_Ajustado_SP_Atacado;
    property Mva_Ajustado_SP_Cd: string read FMva_Ajustado_SP_Cd write FMva_Ajustado_SP_Cd;
    property Mva_Ajustado_SP_Industria: string read FMva_Ajustado_SP_Industria write FMva_Ajustado_SP_Industria;
    property Mva_Ajustado_TO_Atacado: string read FMva_Ajustado_TO_Atacado write FMva_Ajustado_TO_Atacado;
    property Mva_Ajustado_TO_Cd: string read FMva_Ajustado_TO_Cd write FMva_Ajustado_TO_Cd;
    property Mva_Ajustado_TO_Industria: string read FMva_Ajustado_TO_Industria write FMva_Ajustado_TO_Industria;
    property Mva_Importado: string read FMva_Importado write FMva_Importado;
    property Ncm: string read FNcm write FNcm;
    property Ncmex: string read FNcmex write FNcmex;
    property Pauta: Integer read FPauta write FPauta;
    property Pauta_Valor: string read FPauta_Valor write FPauta_Valor;
    property Pis: string read FPis write FPis;
    property Piscofins_Cst_Entrada: string read FPiscofins_Cst_Entrada write FPiscofins_Cst_Entrada;
    property Piscofins_Cst_Saida: string read FPiscofins_Cst_Saida write FPiscofins_Cst_Saida;
    property Piscofins_Naturezarec: string read FPiscofins_Naturezarec write FPiscofins_Naturezarec;
    property Piscofins_Situacao: string read FPiscofins_Situacao write FPiscofins_Situacao;
    property Segmento: string read FSegmento write FSegmento;
    property Subitem: string read FSubitem write FSubitem;
    property Substituicao_Tributaria: string read FSubstituicao_Tributaria write FSubstituicao_Tributaria;
    property Mensagem :string read FMensagem write FMensagem;
  end;

  TRootDTO = class
  private
    FCliente: string;
    FDttransacao: string;
    FErro: Integer;
    FEstado: string;
    FIdtransacao: string;
    FMensagem: string;
    FRegime_Tributario: string;
    [JSONName('tributos')]
    FTributosArray: TArray<TTributosDTO>;
    [GenericListReflect]
    FTributos: TObjectList<TTributosDTO>;
    function GetTributos: TObjectList<TTributosDTO>;
  published
    property Cliente: string read FCliente write FCliente;
    property Dttransacao: string read FDttransacao write FDttransacao;
    property Erro: Integer read FErro write FErro;
    property Estado: string read FEstado write FEstado;
    property Idtransacao: string read FIdtransacao write FIdtransacao;
    property Mensagem: string read FMensagem write FMensagem;
    property Regime_Tributario: string read FRegime_Tributario write FRegime_Tributario;
    property Tributos: TObjectList<TTributosDTO> read GetTributos;
    destructor Destroy; override;
  end;

implementation

{ TRootDTO }

destructor TRootDTO.Destroy;
begin
  GetTributos.Free;
  inherited;
end;

function TRootDTO.GetTributos: TObjectList<TTributosDTO>;
begin
  if not Assigned(FTributos) then
  begin
    FTributos := TObjectList<TTributosDTO>.Create;
    FTributos.AddRange(FTributosArray);
  end;
  Result := FTributos;
end;

end.
